### ISSUE TITLE
Cannot start locally

### ISSUE THREAD

**Issue by July-Tea** [rawgraphs/rawgraphs-app#410]
Facing the problem and don't know why T_T
```
➜  rawgraphs-app-2.0.1 yarn start
yarn run v1.22.22
$ react-scripts start
ℹ ｢wds｣: Project is running at http://192.168.18.113/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/jult/py/rawgraphs-app-2.0.1/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

/Users/jult/py/rawgraphs-app-2.0.1/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/jult/py/rawgraphs-app-2.0.1/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jult/py/rawgraphs-app-2.0.1/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/jult/py/rawgraphs-app-2.0.1/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/jult/py/rawgraphs-app-2.0.1/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/jult/py/rawgraphs-app-2.0.1/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/jult/py/rawgraphs-app-2.0.1/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/jult/py/rawgraphs-app-2.0.1/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/jult/py/rawgraphs-app-2.0.1/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v22.5.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by juratjan123** [comment]
The Environment is M1 MacOS & Sonoma 14.6.1

**Comment by mikima** [comment]
Thanks. This issue seems related to using Yarn 2, and to the issue with openssl (linked to issue #397).

@bianchimro I imagine we should update the project to Yarn2 and to the latest SSL
